// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/ytservice/ytservice.proto

/*
Package ytservicepb is a generated protocol buffer package.

It is generated from these files:
	proto/ytservice/ytservice.proto

It has these top-level messages:
	SearchVideoReq
	SearchVideoResp
*/
package ytservicepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchVideoReq struct {
	VideoName string `protobuf:"bytes,1,opt,name=videoName" json:"videoName,omitempty"`
}

func (m *SearchVideoReq) Reset()                    { *m = SearchVideoReq{} }
func (m *SearchVideoReq) String() string            { return proto.CompactTextString(m) }
func (*SearchVideoReq) ProtoMessage()               {}
func (*SearchVideoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SearchVideoReq) GetVideoName() string {
	if m != nil {
		return m.VideoName
	}
	return ""
}

type SearchVideoResp struct {
	Resp map[string]string `protobuf:"bytes,1,rep,name=resp" json:"resp,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *SearchVideoResp) Reset()                    { *m = SearchVideoResp{} }
func (m *SearchVideoResp) String() string            { return proto.CompactTextString(m) }
func (*SearchVideoResp) ProtoMessage()               {}
func (*SearchVideoResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SearchVideoResp) GetResp() map[string]string {
	if m != nil {
		return m.Resp
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchVideoReq)(nil), "ytservice.SearchVideoReq")
	proto.RegisterType((*SearchVideoResp)(nil), "ytservice.SearchVideoResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for YTservice service

type YTserviceClient interface {
	SearchVideo(ctx context.Context, in *SearchVideoReq, opts ...grpc.CallOption) (*SearchVideoResp, error)
}

type yTserviceClient struct {
	cc *grpc.ClientConn
}

func NewYTserviceClient(cc *grpc.ClientConn) YTserviceClient {
	return &yTserviceClient{cc}
}

func (c *yTserviceClient) SearchVideo(ctx context.Context, in *SearchVideoReq, opts ...grpc.CallOption) (*SearchVideoResp, error) {
	out := new(SearchVideoResp)
	err := grpc.Invoke(ctx, "/ytservice.YTservice/SearchVideo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for YTservice service

type YTserviceServer interface {
	SearchVideo(context.Context, *SearchVideoReq) (*SearchVideoResp, error)
}

func RegisterYTserviceServer(s *grpc.Server, srv YTserviceServer) {
	s.RegisterService(&_YTservice_serviceDesc, srv)
}

func _YTservice_SearchVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTserviceServer).SearchVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ytservice.YTservice/SearchVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTserviceServer).SearchVideo(ctx, req.(*SearchVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _YTservice_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ytservice.YTservice",
	HandlerType: (*YTserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchVideo",
			Handler:    _YTservice_SearchVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ytservice/ytservice.proto",
}

func init() { proto.RegisterFile("proto/ytservice/ytservice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xaf, 0x2c, 0x29, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x45, 0xb0, 0xf4, 0xc0, 0x32,
	0x42, 0x9c, 0x70, 0x01, 0x25, 0x3d, 0x2e, 0xbe, 0xe0, 0xd4, 0xc4, 0xa2, 0xe4, 0x8c, 0xb0, 0xcc,
	0x94, 0xd4, 0xfc, 0xa0, 0xd4, 0x42, 0x21, 0x19, 0x2e, 0xce, 0x32, 0x10, 0xdb, 0x2f, 0x31, 0x37,
	0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0x21, 0xa0, 0xd4, 0xc2, 0xc8, 0xc5, 0x8f, 0xa2,
	0xa1, 0xb8, 0x40, 0xc8, 0x82, 0x8b, 0xa5, 0x28, 0xb5, 0xb8, 0x40, 0x82, 0x51, 0x81, 0x59, 0x83,
	0xdb, 0x48, 0x45, 0x0f, 0x61, 0x1d, 0x9a, 0x4a, 0x3d, 0x10, 0xe1, 0x9a, 0x57, 0x52, 0x54, 0x19,
	0x04, 0xd6, 0x21, 0x65, 0xce, 0xc5, 0x09, 0x17, 0x12, 0x12, 0xe0, 0x62, 0xce, 0x4e, 0xad, 0x84,
	0x5a, 0x09, 0x62, 0x0a, 0x89, 0x70, 0xb1, 0x96, 0x25, 0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x81, 0xc5,
	0x20, 0x1c, 0x2b, 0x26, 0x0b, 0x46, 0xa3, 0x60, 0x2e, 0xce, 0xc8, 0x10, 0xa8, 0x2d, 0x42, 0x6e,
	0x5c, 0xdc, 0x48, 0x16, 0x09, 0x49, 0xe2, 0x72, 0x40, 0xa1, 0x94, 0x14, 0x6e, 0xb7, 0x29, 0x31,
	0x38, 0xf1, 0x46, 0x71, 0xc3, 0xa5, 0x0b, 0x92, 0x92, 0xd8, 0xc0, 0x81, 0x65, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x45, 0xa6, 0x41, 0xc2, 0x4f, 0x01, 0x00, 0x00,
}
